server:
  port: 80

spring:
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: none



  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/crud
    url : jdbc:h2:tcp://localhost/~/crud
    username: sa
    password: 1234

